name: CI

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake libgtest-dev
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON
      - name: Build
        run: cmake --build build -j "$(nproc)"
      - name: Test
        run: ctest --test-dir build -j "$(nproc)" --output-on-failure
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake libgtest-dev \
            clang-format clang-tidy
      - name: CMake
        run: cmake -S . -B build -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON
      - name: clang-format
        run: |
          find . \( -name '*.cc' -or -name '*.h' \) -exec \
            clang-format --Werror --dry-run --verbose {} +
      - name: clang-tidy
        run: |
          find . \( -name '*.cc' -or -name '*.h' \) -exec \
            clang-tidy -p build --warnings-as-errors='*' {} +
